instanceId: "18662553"

http:
  listener:
    host: "0.0.0.0"
    port: "8081"
  requester:
    customer:
      sapi:
        host: "customer-sapi-app888888.us-e2.cloudhub.io"
        port: ""
        pathCustomerState: "/api/customerState"
        pathVerification: "/api/verification"
        pathCustomerRegistration: "/api/customers/registration"
      papi:
        host: "customer-papi-app888888.us-e2.cloudhub.io"
        port: ""
        pathCustomerState: "/api/customerState"
        pathVerification: "/api/verification"

    
        
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                        
                                                                            
                                                                                
                                                                                    
                                                                                        
                                                                                            
                                                                                                
                                                                                                    
                                                                                                        
                                                                                                            
                                                                                                                
                                                                                                                    
                                                                                                                        
                                                                                                                            
                                                                                                                                
                                                                                                                                    
                                                                                                                                            
sfdc:
  username: "mulesoftenthusiast@gmail.com"
  password: "Silky12345"
  securityToken: "AFhvGSow32ZWhX331GcMM9my"



